name = "Minecraft Packwiz"
author = "Evilenzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ee4e13aacd46ffdb83accc31d3b5a85f3711bd17072ed60ce2051c553fc00ff"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
