name = "Minecraft Packwiz"
author = "Evilenzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2828574dfd1f619134a239a092055494f922a01e4ab8e8bed5a30b1c2d024f5"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
