name = "Minecraft Packwiz"
author = "Evilenzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9414b0229b9486b8f3a77ac84f9c874f4647dc10988ae45c18060f7ce8bdd0ef"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
